import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { ApiClient } from "../api-client.js";
import { registerUserTools } from "./users.js";
import { registerPropertyTools } from "./properties.js";
import { registerBookingTools } from "./bookings.js";
import { registerGuestTools } from "./guests.js";
import { registerVendorTools } from "./vendors.js";
import { registerTaskTools } from "./tasks.js";
import { registerTemplateTools } from "./templates.js";
import { registerLeadTools } from "./leads.js";
import { registerPipelineStageTools } from "./pipeline-stages.js";
import { registerReportTools } from "./reports.js";
import { registerNoteTools } from "./notes.js";
import { registerReminderTools } from "./reminders.js";
import { registerNotificationTools } from "./notifications.js";
import { registerEntityTools } from "./entities.js";
import { registerPaymentTools, registerStripeAccountTools } from "./payments.js";
import { registerInventoryTools } from "./inventory.js";
import { registerConversationTools } from "./conversations.js";
import { registerMessageTemplateTools } from "./message-templates.js";
import { registerSubscriptionTools } from "./subscriptions.js";
import { registerPollTools } from "./polls.js";
import { registerReportWidgetTools } from "./report-widgets.js";
import { registerAdminUtilityTools } from "./admin.js";
import { registerCampaignTools } from "./campaigns.js";
import { registerImportJobTools } from "./import-jobs.js";

export function registerAllTools(server: McpServer, client: ApiClient) {
  registerUserTools(server, client);
  registerPropertyTools(server, client);
  registerBookingTools(server, client);
  registerGuestTools(server, client);
  registerVendorTools(server, client);
  registerTaskTools(server, client);
  registerTemplateTools(server, client);
  registerLeadTools(server, client);
  registerPipelineStageTools(server, client);
  registerReportTools(server, client);
  registerNoteTools(server, client);
  registerReminderTools(server, client);
  registerNotificationTools(server, client);
  registerEntityTools(server, client);
  registerPaymentTools(server, client);
  registerStripeAccountTools(server, client);
  registerInventoryTools(server, client);
  registerConversationTools(server, client);
  registerMessageTemplateTools(server, client);
  registerSubscriptionTools(server, client);
  registerPollTools(server, client);
  registerReportWidgetTools(server, client);
  registerAdminUtilityTools(server, client);
  registerCampaignTools(server, client);
  registerImportJobTools(server, client);
}
